#!/usr/bin/env python
import getpass
import mechanize
import sys

import lxml.html

assert len(sys.argv) == 2 and sys.argv[1].isalnum(), "Usage: %s <username>" % sys.argv[0]

mech = mechanize.Browser()
mech.open("https://mobilbank.swedbank.se/banking/swedbank/login.html")
mech.select_form(nr=0)
mech.form.set_value(sys.argv[1], name="xyz")
mech.submit()
mech.select_form(nr=0)
mech.form.set_value(getpass.getpass(), name="zyx")
mech.submit()
tree = lxml.html.fromstring(mech.follow_link(mech.find_link(url='/banking/swedbank/accounts.html')).get_data())
for dd in tree.find_class("list-content").pop().findall("dd"):
    print "%s\t%s" % (dd.find_class("name").pop().text.strip(),
                      dd.find_class("amount").pop().text.replace(" ", ""))
